language: node_js
node_js:
  - "4.3"

install:
  - sudo apt-get update
  - sudo apt-get install -y jq

script:
  - curl "https://www.browserstack.com/app-automate/sample-apps/ios/BStackSampleApp.ipa" -o "$TRAVIS_BUILD_DIR/BStackSampleApp.ipa"
  - export BROWSERSTACK_APP_ID=`(curl -u "pankajahuja1:aCxhDStUopf8tsyz4d55" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "file=@$TRAVIS_BUILD_DIR/BStackSampleApp.ipa" | jq -r .app_url)`
  - echo $BROWSERSTACK_APP_ID
  - cd ios
  - npm install
  - npm run single
