language: node_js
node_js:
  - "4.3"

install:
  - sudo apt-get update
  - sudo apt-get install -y jq

script:
  - curl "https://www.browserstack.com/app-automate/sample-apps/ios/BStackSampleApp.ipa" -o "BStackSampleApp.ipa"
  - export BROWSERSTACK_APP_ID=`(curl -u "`$BROWSERSTACK_USERNAME`:`$BROWSERSTACK_APP_ID`" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "file=@BStackSampleApp.ipa" | jq .app_url)`
  - echo $BROWSERSTACK_APP_ID
  - cd ios
  - npm install
  - npm run single
